### ISSUE TITLE
Remove entrypoint definition

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-php#3]
Since the upstream image (https://github.com/wunderkraut/alpine-php) has now been fixed with a working entrypoint there is no need to override it any more in this image.

**Comment by james-nesbitt** [comment]
Interesting that https://github.com/wunderkraut/wundertools-image-fuzzy-php-developer was not affected.

**Comment by james-nesbitt** [comment]
Solution is to remove these lines from the Dockerfile:

````

###
# Correct entrypoint
ENTRYPOINT ["/usr/sbin/php-fpm7", "--nodaemonize"]
````

**Comment by aleksijohansson** [comment]
@james-nesbitt Maybe it was just not tested?
